package com.main.Enum;

public enum DesignationMaster {

	INTERN,
    TRAINEE_ENGINEER,
    JUNIOR_ENGINEER,
    SOFTWARE_ENGINEER,
    SENIOR_SOFTWARE_ENGINEER,
    LEAD_ENGINEER,
    ASSOCIATE_ARCHITECT,
    ARCHITECT,
    SENIOR_ARCHITECT,
    ENGINEERING_MANAGER,
    SENIOR_ENGINEERING_MANAGER,
    DIRECTOR,
    SENIOR_DIRECTOR,
    VICE_PRESIDENT,
    SENIOR_VICE_PRESIDENT,
    CTO,   
    CEO;
	 

}
